export type AirshowEntry = {
  title: string;
  source: string;
  sourceUrl: string;
  spottedBy: string;
  spottedOn: string;
  tags: string[];
  what: string;
  why: string;
  color: "sky" | "butter" | "coral" | "mint" | "cream";
};

export const AIRSHOW: AirshowEntry[] = [
  {
    title: "Arc",
    source: "The Browser Company",
    sourceUrl: "https://arc.net/",
    spottedBy: "julian",
    spottedOn: "2026-06-10",
    tags: ["browser", "design", "productivity"],
    what: "A browser that rethinks the basics, with tabs in a sidebar, separate spaces for different parts of your life, and small touches like split view and quick previews.",
    why: "A rare case of someone redesigning a thing we all take for granted, and clearly sweating every detail.",
    color: "cream",
  },
  {
    title: "Cursor Composer",
    source: "Cursor",
    sourceUrl: "https://www.cursor.com",
    spottedBy: "julian",
    spottedOn: "2026-05-22",
    tags: ["coding", "agents", "ide"],
    what: "Multi-file agent inside the editor. You describe an intent across the whole repo and it edits, runs, and iterates until tests pass.",
    why: "Feels like the first version of an AI pair that actually understands a codebase. Worth seeing how they made the diff review feel safe.",
    color: "sky",
  },
  {
    title: "Granola",
    source: "Granola.ai",
    sourceUrl: "https://www.granola.ai",
    spottedBy: "julian",
    spottedOn: "2026-05-19",
    tags: ["meetings", "notes", "audio"],
    what: "Meeting notes that combine your hand-typed shorthand with full audio transcription. The output is a single doc that reads like your notes, only better.",
    why: "Beautifully restrained AI. Doesn't try to take over the meeting, helps you write the note you would have written.",
    color: "butter",
  },
  {
    title: "PostHog",
    source: "PostHog",
    sourceUrl: "https://posthog.com/",
    spottedBy: "julian",
    spottedOn: "2026-06-09",
    tags: ["analytics", "product", "open-source"],
    what: "An all-in-one product analytics platform that bundles event tracking, session replay, feature flags and experiments, with an AI layer that pulls insights and builds experiments from a plain question.",
    why: "It does a lot, but what stays with you is the brand. It is opinionated, funny, and clearly made by the people who use it.",
    color: "coral",
  },
  {
    title: "Lusion",
    source: "Lusion",
    sourceUrl: "https://lusion.co/",
    spottedBy: "julian",
    spottedOn: "2026-06-08",
    tags: ["creative", "webgl", "studio"],
    what: "A Bristol studio making award-winning interactive web work, mixing 3D, motion and development into sites that feel closer to an experience than a page.",
    why: "Reference-grade craft for the web. Worth a look whenever you need reminding how high the bar can go.",
    color: "mint",
  },
  {
    title: "Krea Realtime",
    source: "Krea",
    sourceUrl: "https://www.krea.ai",
    spottedBy: "julian",
    spottedOn: "2026-05-15",
    tags: ["image", "generative", "creative"],
    what: "Generates images at the speed you can sketch. Draw a rough shape and a finished illustration appears as you move.",
    why: "Wired generative AI directly into the hand. Feels less like a tool and more like an instrument.",
    color: "cream",
  },
  {
    title: "Sprive",
    source: "Sprive",
    sourceUrl: "https://sprive.com/",
    spottedBy: "julian",
    spottedOn: "2026-06-07",
    tags: ["fintech", "mobile", "money"],
    what: "A mobile app that helps you pay off your mortgage sooner, rounding up spending and turning retailer cashback into overpayments, with remortgage deals built in.",
    why: "A clear, single job done well. It takes something dull and a little scary and makes it feel manageable.",
    color: "sky",
  },
  {
    title: "Scenescapes",
    source: "Annas Rahman",
    sourceUrl: "https://uispace.org/index.html",
    spottedBy: "julian",
    spottedOn: "2026-06-06",
    tags: ["design", "interface", "speculative"],
    what: "A gallery of twenty working interfaces from imagined futures by designer Annas Rahman, from terraforming consoles to particle accelerators, all interactive and free to poke at.",
    why: "A lovely bit of speculative interface design. Good fuel when you want to push past the obvious layout.",
    color: "butter",
  },
  {
    title: "Sim CFO",
    source: "Sim CFO",
    sourceUrl: "https://sim-cfo.com/",
    spottedBy: "julian",
    spottedOn: "2026-06-05",
    tags: ["simulation", "finance", "learning"],
    what: "A simulation that drops you in as the interim CFO of a struggling company, making real calls on M&A, board dynamics and cash, with feedback after each decision.",
    why: "A smart use of simulation for learning. You practise the hard decisions somewhere they don't cost anything.",
    color: "mint",
  },
  {
    title: "Detach",
    source: "Detach",
    sourceUrl: "https://www.detach-app.de/",
    spottedBy: "julian",
    spottedOn: "2026-06-04",
    tags: ["wellbeing", "focus", "mobile"],
    what: "A screen-time app built around blocks you can't easily skip, so cutting down on doomscrolling leans on friction you set up in advance rather than willpower.",
    why: "It understands that the honest fix is making the bad habit harder, not nagging you about it.",
    color: "coral",
  },
  {
    title: "Magic Inbox",
    source: "Superhuman",
    sourceUrl: "https://superhuman.com",
    spottedBy: "julian",
    spottedOn: "2026-05-05",
    tags: ["email", "summarisation", "productivity"],
    what: "Inbox triage that writes a one-line summary of every thread, drafts a reply in your tone, and surfaces what needs you today.",
    why: "Restraint as a feature. Doesn't summarise everything, only what you would have skimmed.",
    color: "coral",
  },
];
