export type AirshowCategory =
  | "ai"
  | "craft"
  | "play"
  | "tools"
  | "money"
  | "wellbeing";

export type AirshowEntry = {
  title: string;
  source: string;
  sourceUrl: string;
  spottedBy: string;
  spottedOn: string;
  tags: string[];
  categories: AirshowCategory[];
  what: string;
  why: string;
  color: "sky" | "butter" | "coral" | "mint" | "cream";
};

export const AIRSHOW_CATEGORY_LABEL: Record<AirshowCategory, string> = {
  ai: "AI tools",
  craft: "Design & craft",
  play: "Just for fun",
  tools: "Tools we work in",
  money: "Money",
  wellbeing: "Wellbeing",
};

// Display order for the filter row (All is prepended in the UI).
export const AIRSHOW_CATEGORY_ORDER: AirshowCategory[] = [
  "ai",
  "craft",
  "play",
  "tools",
  "money",
  "wellbeing",
];

export const AIRSHOW: AirshowEntry[] = [
  {
    title: "Stonk Rider",
    source: "Stonk Rider",
    sourceUrl: "https://stonkrider.com/",
    spottedBy: "julian",
    spottedOn: "2026-06-10",
    tags: ["fun", "finance", "interactive"],
    categories: ["money", "play"],
    what: "Ride any stock chart like a Line Rider track. Pick a ticker and a little motocross bike runs the real price line, backflipping up the rallies and piling up through the crashes.",
    why: "A straight lift of Line Rider, the hit game from fifteen years ago, pointed at real market data. The kind of small, silly idea that lands because it is built so well.",
    color: "coral",
  },
  {
    title: "Neal.fun",
    source: "Neal Agarwal",
    sourceUrl: "https://neal.fun/",
    spottedBy: "julian",
    spottedOn: "2026-06-10",
    tags: ["toys", "interactive", "web"],
    categories: ["play"],
    what: "A long-running collection of interactive toys from Neal Agarwal, like scrolling to the bottom of the deep sea, spending Bill Gates' money, or beating The Password Game.",
    why: "The benchmark for the well-made web toy. Each one is a tiny, complete idea that someone clearly had fun building.",
    color: "butter",
  },
  {
    title: "Infinite Craft",
    source: "Neal Agarwal",
    sourceUrl: "https://neal.fun/infinite-craft/",
    spottedBy: "julian",
    spottedOn: "2026-06-10",
    tags: ["ai", "game", "generative"],
    categories: ["play", "ai"],
    what: "Drag two things together and an AI invents whatever they would combine into, starting from earth, wind, fire and water and spiralling out from there.",
    why: "A lovely example of AI as a toy rather than a tool. Easy to lose half an hour to it.",
    color: "mint",
  },
  {
    title: "Radio Garden",
    source: "Radio Garden",
    sourceUrl: "https://radio.garden/",
    spottedBy: "julian",
    spottedOn: "2026-06-10",
    tags: ["audio", "map", "radio"],
    categories: ["play"],
    what: "Spin a globe dotted with green points and tune straight into a live local radio station anywhere on earth.",
    why: "A simple idea done beautifully. Surprisingly moving to drop in on a late-night station on the other side of the world.",
    color: "sky",
  },
  {
    title: "Window Swap",
    source: "Window Swap",
    sourceUrl: "https://www.window-swap.com/",
    spottedBy: "julian",
    spottedOn: "2026-06-10",
    tags: ["calm", "video", "web"],
    categories: ["play"],
    what: "Open a new window and you are looking out of a stranger's, somewhere in the world, for as long as you like.",
    why: "Calm rather than silly. A small reminder that the web can slow you down as well as speed you up.",
    color: "cream",
  },
  {
    title: "Bruno Simon",
    source: "Bruno Simon",
    sourceUrl: "https://bruno-simon.com/",
    spottedBy: "julian",
    spottedOn: "2026-06-10",
    tags: ["webgl", "3d", "portfolio"],
    categories: ["play", "craft"],
    what: "A personal portfolio you explore by driving a little toy car around a 3D world, bumping into the projects as you go.",
    why: "The site everyone points to when they talk about playful web craft. It still holds up years later.",
    color: "butter",
  },
  {
    title: "Lovable",
    source: "Lovable",
    sourceUrl: "https://lovable.dev/",
    spottedBy: "julian",
    spottedOn: "2026-06-10",
    tags: ["vibecoding", "ai", "no-code"],
    categories: ["ai"],
    what: "Describe the app you want in plain language and it builds a working, full-stack version you can edit, host and ship, with no setup.",
    why: "One of the clearest examples of vibecoding. It puts a real product within reach of people who don't write code.",
    color: "sky",
  },
  {
    title: "NotebookLM",
    source: "Google",
    sourceUrl: "https://notebooklm.google.com/",
    spottedBy: "julian",
    spottedOn: "2026-06-10",
    tags: ["ai", "research", "audio"],
    categories: ["ai"],
    what: "Give it your own documents and it answers questions grounded in them, with citations, or turns the lot into a surprisingly listenable two-host podcast.",
    why: "The grounded answers are useful, but the audio overviews are the party trick. Genuinely good for getting across a pile of research.",
    color: "mint",
  },
  {
    title: "Perplexity",
    source: "Perplexity",
    sourceUrl: "https://www.perplexity.ai/",
    spottedBy: "julian",
    spottedOn: "2026-06-10",
    tags: ["ai", "search", "research"],
    categories: ["ai"],
    what: "An answer engine that searches the web and replies with a short, cited summary rather than a page of blue links.",
    why: "The cleanest of the AI search tools. A good first stop when you want a fast, sourced answer.",
    color: "coral",
  },
  {
    title: "ElevenLabs",
    source: "ElevenLabs",
    sourceUrl: "https://elevenlabs.io/",
    spottedBy: "julian",
    spottedOn: "2026-06-10",
    tags: ["ai", "voice", "audio"],
    categories: ["ai"],
    what: "Text to speech and voice cloning that produces audio hard to tell from a real recording, across a wide range of voices and languages.",
    why: "The quality bar for synthetic voice right now. Worth hearing once just to recalibrate what's possible.",
    color: "butter",
  },
  {
    title: "Arc",
    source: "The Browser Company",
    sourceUrl: "https://arc.net/",
    spottedBy: "julian",
    spottedOn: "2026-06-10",
    tags: ["browser", "design", "productivity"],
    categories: ["tools", "craft"],
    what: "A browser that rethinks the basics, with tabs in a sidebar, separate spaces for different parts of your life, and small touches like split view and quick previews.",
    why: "A rare case of someone redesigning a thing we all take for granted, and clearly sweating every detail.",
    color: "cream",
  },
  {
    title: "Linear",
    source: "Linear",
    sourceUrl: "https://linear.app",
    spottedBy: "julian",
    spottedOn: "2026-06-10",
    tags: ["product", "tools", "craft"],
    categories: ["tools", "craft"],
    what: "Issue tracking and project planning built for speed, with keyboard-first navigation and a clear opinion about how teams should plan work.",
    why: "It moved the bar for how good an internal tool can feel. Hard to go back to anything slower.",
    color: "sky",
  },
  {
    title: "Raycast",
    source: "Raycast",
    sourceUrl: "https://www.raycast.com",
    spottedBy: "julian",
    spottedOn: "2026-06-10",
    tags: ["mac", "productivity", "ai"],
    categories: ["ai"],
    what: "A Mac launcher that quietly replaces a dozen small tools, from clipboard history to window management, with AI and an extension store layered on top.",
    why: "A masterclass in small, well-made interactions. Every command feels like someone cared about it.",
    color: "butter",
  },
  {
    title: "Cosmos",
    source: "Cosmos",
    sourceUrl: "https://www.cosmos.so",
    spottedBy: "julian",
    spottedOn: "2026-06-09",
    tags: ["creative", "inspiration", "design"],
    categories: ["craft"],
    what: "A visual discovery tool for collecting and arranging images, videos and references into boards that actually look good.",
    why: "Designers tend to fall for it fast. A calmer, more beautiful way to gather inspiration.",
    color: "coral",
  },
  {
    title: "Wispr Flow",
    source: "Wispr",
    sourceUrl: "https://wisprflow.ai",
    spottedBy: "julian",
    spottedOn: "2026-06-09",
    tags: ["voice", "writing", "ai"],
    categories: ["ai"],
    what: "Voice dictation that turns speech into clean, punctuated text in any app, fast enough to use instead of typing.",
    why: "One of those tools that feels like magic the first time. It quietly changes how you write at a desk.",
    color: "mint",
  },
  {
    title: "Napkin",
    source: "Napkin",
    sourceUrl: "https://www.napkin.ai",
    spottedBy: "julian",
    spottedOn: "2026-06-09",
    tags: ["design", "diagrams", "ai"],
    categories: ["ai", "craft"],
    what: "Paste in your writing and it generates editable diagrams and visuals to match, ready to drop into a deck or doc.",
    why: "Takes the worst part of making a deck and makes it quick. Handy whenever words need a picture.",
    color: "cream",
  },
  {
    title: "Pitch",
    source: "Pitch",
    sourceUrl: "https://pitch.com",
    spottedBy: "julian",
    spottedOn: "2026-06-09",
    tags: ["presentations", "design", "collaboration"],
    categories: ["tools", "craft"],
    what: "Presentation software built for teams, with sharp templates, real-time collaboration and a level of polish most deck tools skip.",
    why: "Proof that deck software doesn't have to feel dated. The defaults alone make better-looking slides.",
    color: "butter",
  },
  {
    title: "Cursor Composer",
    source: "Cursor",
    sourceUrl: "https://www.cursor.com",
    spottedBy: "julian",
    spottedOn: "2026-05-22",
    tags: ["coding", "agents", "ide"],
    categories: ["ai", "tools"],
    what: "Multi-file agent inside the editor. You describe an intent across the whole repo and it edits, runs, and iterates until tests pass.",
    why: "Feels like the first version of an AI pair that actually understands a codebase. Worth seeing how they made the diff review feel safe.",
    color: "sky",
  },
  {
    title: "Granola",
    source: "Granola.ai",
    sourceUrl: "https://www.granola.ai",
    spottedBy: "julian",
    spottedOn: "2026-05-19",
    tags: ["meetings", "notes", "audio"],
    categories: ["ai", "tools"],
    what: "Meeting notes that combine your hand-typed shorthand with full audio transcription. The output is a single doc that reads like your notes, only better.",
    why: "Beautifully restrained AI. Doesn't try to take over the meeting, helps you write the note you would have written.",
    color: "butter",
  },
  {
    title: "PostHog",
    source: "PostHog",
    sourceUrl: "https://posthog.com/",
    spottedBy: "julian",
    spottedOn: "2026-06-09",
    tags: ["analytics", "product", "open-source"],
    categories: ["tools"],
    what: "An all-in-one product analytics platform that bundles event tracking, session replay, feature flags and experiments, with an AI layer that pulls insights and builds experiments from a plain question.",
    why: "It does a lot, but what stays with you is the brand. It is opinionated, funny, and clearly made by the people who use it.",
    color: "coral",
  },
  {
    title: "Lusion",
    source: "Lusion",
    sourceUrl: "https://lusion.co/",
    spottedBy: "julian",
    spottedOn: "2026-06-08",
    tags: ["creative", "webgl", "studio"],
    categories: ["craft"],
    what: "A Bristol studio making award-winning interactive web work, mixing 3D, motion and development into sites that feel closer to an experience than a page.",
    why: "Reference-grade craft for the web. Worth a look whenever you need reminding how high the bar can go.",
    color: "mint",
  },
  {
    title: "Krea Realtime",
    source: "Krea",
    sourceUrl: "https://www.krea.ai",
    spottedBy: "julian",
    spottedOn: "2026-05-15",
    tags: ["image", "generative", "creative"],
    categories: ["ai", "craft"],
    what: "Generates images at the speed you can sketch. Draw a rough shape and a finished illustration appears as you move.",
    why: "Wired generative AI directly into the hand. Feels less like a tool and more like an instrument.",
    color: "cream",
  },
  {
    title: "Sprive",
    source: "Sprive",
    sourceUrl: "https://sprive.com/",
    spottedBy: "julian",
    spottedOn: "2026-06-07",
    tags: ["fintech", "mobile", "money"],
    categories: ["money"],
    what: "A mobile app that helps you pay off your mortgage sooner, rounding up spending and turning retailer cashback into overpayments, with remortgage deals built in.",
    why: "A clear, single job done well. It takes something dull and a little scary and makes it feel manageable.",
    color: "sky",
  },
  {
    title: "Scenescapes",
    source: "Annas Rahman",
    sourceUrl: "https://uispace.org/index.html",
    spottedBy: "julian",
    spottedOn: "2026-06-06",
    tags: ["design", "interface", "speculative"],
    categories: ["craft"],
    what: "A gallery of twenty working interfaces from imagined futures by designer Annas Rahman, from terraforming consoles to particle accelerators, all interactive and free to poke at.",
    why: "A lovely bit of speculative interface design. Good fuel when you want to push past the obvious layout.",
    color: "butter",
  },
  {
    title: "Sim CFO",
    source: "Sim CFO",
    sourceUrl: "https://sim-cfo.com/",
    spottedBy: "julian",
    spottedOn: "2026-06-05",
    tags: ["simulation", "finance", "learning"],
    categories: ["money"],
    what: "A simulation that drops you in as the interim CFO of a struggling company, making real calls on M&A, board dynamics and cash, with feedback after each decision.",
    why: "A smart use of simulation for learning. You practise the hard decisions somewhere they don't cost anything.",
    color: "mint",
  },
  {
    title: "Detach",
    source: "Detach",
    sourceUrl: "https://www.detach-app.de/",
    spottedBy: "julian",
    spottedOn: "2026-06-04",
    tags: ["wellbeing", "focus", "mobile"],
    categories: ["wellbeing"],
    what: "A screen-time app built around blocks you can't easily skip, so cutting down on doomscrolling leans on friction you set up in advance rather than willpower.",
    why: "It understands that the honest fix is making the bad habit harder, not nagging you about it.",
    color: "coral",
  },
  {
    title: "Magic Inbox",
    source: "Superhuman",
    sourceUrl: "https://superhuman.com",
    spottedBy: "julian",
    spottedOn: "2026-05-05",
    tags: ["email", "summarisation", "productivity"],
    categories: ["ai"],
    what: "Inbox triage that writes a one-line summary of every thread, drafts a reply in your tone, and surfaces what needs you today.",
    why: "Restraint as a feature. Doesn't summarise everything, only what you would have skimmed.",
    color: "coral",
  },
];
